name: lion
channels:
  - conda-forge
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2022.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2022.1.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openssl=1.1.1w
  - pip=23.2.1
  - python=3.8.12
  - python_abi=3.8
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - typing_extensions=4.7.1
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.19.0
      - anyio==4.0.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.0
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - calmsize==0.1.3
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.0
      - click==8.1.7
      - clip==1.0
      - comet-ml==3.31.21
      - comm==0.1.4
      - configobj==5.0.8
      - contourpy==1.1.1
      - cycler==0.12.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - diffusers==0.11.1
      - docker-pycreds==0.4.0
      - dulwich==0.21.6
      - einops==0.4.0
      - entrypoints==0.4
      - everett==3.2.0
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - filelock==3.12.4
      - fonttools==4.43.0
      - fqdn==1.5.1
      - fsspec==2023.9.2
      - ftfy==6.1.1
      - gitdb==4.0.10
      - gitpython==3.1.37
      - huggingface-hub==0.17.3
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - ipykernel==6.25.2
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==7.4.9
      - jupyter-core==5.3.2
      - jupyter-events==0.7.0
      - jupyter-packaging==0.12.3
      - jupyter-server==2.7.3
      - jupyter-server-fileid==0.9.0
      - jupyter-server-terminals==0.4.4
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - loguru==0.7.2
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - ninja==1.10.2.3
      - notebook==6.5.6
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - open3d==0.13.0
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.11.0
      - prometheus-client==0.17.1
      - promise==2.3
      - prompt-toolkit==3.0.39
      - protobuf==3.19.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==24.0.1
      - referencing==0.30.2
      - regex==2023.10.3
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.4
      - scikit-learn==1.3.1
      - scipy==1.10.1
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - sentry-sdk==1.31.0
      - shortuuid==1.0.11
      - simplejson==3.19.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - tabulate==0.9.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomlkit==0.12.1
      - tornado==6.3.3
      - tqdm==4.66.1
      - traitlets==5.11.2
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.6
      - wandb==0.12.10
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.3.3
      - widgetsnbextension==4.0.9
      - wrapt==1.15.0
      - wurlitzer==3.0.3
      - y-py==0.6.2
      - yaspin==2.5.0
      - ypy-websocket==0.8.4
      - zipp==3.17.0
